export const A4_DIMENSIONS = {
  WIDTH: 794, 
  HEIGHT: 1123, 
  MARGINS: {
    TOP: 96, 
    BOTTOM: 96, 
    LEFT: 72, 
    RIGHT: 72, 
  },
} as const;

export const CONTENT_AREA = {
  WIDTH:
    A4_DIMENSIONS.WIDTH -
    A4_DIMENSIONS.MARGINS.LEFT -
    A4_DIMENSIONS.MARGINS.RIGHT,
  HEIGHT:
    A4_DIMENSIONS.HEIGHT -
    A4_DIMENSIONS.MARGINS.TOP -
    A4_DIMENSIONS.MARGINS.BOTTOM,
} as const;
